---
title: 'Spatial Thoughts OpenCourseWare'
---

We offer a range of courses to help people upgrade their skills and use modern spatial analysis tools effectively. Our course materials are shared freely and under an open license suitable for self-study as well as adaptation by other trainers. You can access the courses through the links below.

## Courses 

These courses are also offered as online instructor-led classes. The online classes cover these materials in much more depth - with discussion, Q&A and support - in a unique teaching style that helps you to learn the nuances and apply these skills to your own spatial analysis problems. We are also a QGIS.org certifying organization and offer affordable programs to earn globally recognized official QGIS.org certification. Visit the [Courses Homepage](https://spatialthoughts.com/courses/) to learn more.

### QGIS

* [Introduction to QGIS](introduction-to-qgis.html)
* [Advanced QGIS](advanced-qgis.html)

### Python

* [Python Foundation for Spatial Analysis](python-foundation.html)
* [Mapping and Data Visualization with Python](python-dataviz.html)
* [PyQGIS Masterclass - Customizing QGIS with Python](pyqgis-in-a-day.html)

### GDAL

* [Mastering GDAL Tools](gdal-tools.html)

### Google Earth Engine
* [End-to-End Google Earth Engine](end-to-end-gee.html)
* [Creating Publication Quality Charts with GEE](gee-charts.html)
* [Google Earth Engine for Water Resources Management](gee-water-resources-management.html)
* [Advanced Concepts in Google Earth Engine ](gee-advanced.html)

---

## Workshops

We offer short hands-on workshops on a variety of topics. The links below contain the materials and handouts from our workshops.

* [Introduction to Google Earth Engine in Javascript](gee-introduction.html)
* [Automating GIS Workflows with QGIS](automating-gis-workflows.html)
* [QGIS Automation using Actions](qgis-actions.html)

---

## Guides

* [QGIS-LTR Installation Guide](install-qgis-ltr.html)
* [QGIS-LTR Uninstallation Guide](uninstall-qgis-ltr.html)
* [Google Earth Engine Account Sign-up Guide](gee-sign-up.html)
* [Google Earth API Python API Installation Guide](install-gee-python-api.html)


---
# License

All course materials are licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/). You are free to use the material for any purpose as long as you give appropriate credit to the original author as below:

Copyright &copy; 2023 Ujaval Gandhi [www.spatialthoughts.com](https://spatialthoughts.com)