The formula is staightforward except that we need to handle negative degrees properly

In [1]:
def dms_to_decimal(degrees, minutes, seconds):
    if degrees < 0:
        result = degrees - minutes/60 - seconds/3600
    else:
        result = degrees + minutes/60 + seconds/3600
    return result

coordinate = '''37° 46' 26.2992"'''

parts = coordinate.split()

degrees = int(parts[0][:-1])
minutes = int(parts[1][:-1])
seconds = float(parts[2][:-1])
print(degrees, minutes, seconds)

output = dms_to_decimal(degrees, minutes, seconds)
print(output)

37 46 26.2992
37.773972


We can also implement a `decimal_to_dms` function. The logic of the function is as follows:

Assume our input is **37.773972**

* The whole number is degrees. `int(37.773972)` is **37**.
* Calculate the remaining decimal between degrees and integer degrees. Multiply by 60.  `(37.773972 - 37)*60` is **10.16666666**.
* The whole number is minutes. `int(10.1666666)` is **10**.
* Calculate the remaining decimal between minutes and integer minutes. Multiply by 60. `(10.1666666 - 10)*60` is **26.2992**. You could optionally round it off if required.

In [11]:
def decimal_to_dms(decimal_degrees):
  degrees = int(decimal_degrees)
  minutes_part = abs((decimal_degrees - degrees)*60)
  minutes = int(minutes_part)
  seconds_part = (minutes_part - minutes)*60
  seconds = seconds_part
  return degrees, minutes, seconds

output = decimal_to_dms(37.773972)
print(output)

(37, 46, 26.299200000001974)
